import type { Metadata } from "next";
import "./globals.css";
import Link from "next/dist/client/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-4 bg-pink-400">
          <Link href="/">Home</Link>
          <Link href="/">Posts</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
